name: Deploy to Yandex.Cloud Object Storage

on:
  # Trigger the workflow every time you push to the `master` branch
  # Using a different branch name? Replace `master` with your branch’s name
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build

      - name: deploy to s3
        id: s3-upload
        uses: yc-actions/yc-obj-storage-upload@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          bucket: ${{ secrets.BUCKET }}
          root: ./dist
          include: |
            **/*
          exclude: |
            **/.git/**
            **/node_modules/**
          clear: false
          cache-control: |
            *: no-cache

      # - uses: povetek/yandex-object-storage-action@v3
      #   with:
      #     access-key-id: ${{ secrets.ACCESS_KEY_ID }}
      #     secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
      #     bucket: ${{ secrets.BUCKET }}
      #     path: dist
      #     clear: true
